baseURL: https://example.org/
languageCode: en-us
title: 姜跃锋的文档
theme: digital-garden-hugo-theme
googleAnalytics: UA-PROPERTY_ID
Params:
  description: My Digital Garden on the Internet
  images: /digital-garden-logo.png
  newsletter:
    description: A curated weekly digest once a week to your mailbox
    path: https://www.getrevue.co/profile/username/add_subscriber
    title: ''
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Articles
      url: /articles
      weight: 2
    - name: Portfolio
      url: /portfolio
      weight: 3
    - name: Stack
      url: /stack
      weight: 4
    - name: Polywork
      url: https://polywork.com
      weight: 5
  social:
    - name: Twitter
      url: https://twitter.com
      weight: 1
    - name: GitHub
      url: https://github.com
      weight: 2
    - name: LinkedIn
      url: https://linkedin.com
      weight: 3
    - name: Instagram
      url: https://instagram.com
      weight: 4
    - name: Dribbble
      url: https://dribbble.com
      weight: 5
    - name: Codepen
      url: https://codepen.io
      weight: 6
    - name: Twitch
      url: https://twitch.com
      weight: 7
    - name: Email
      url: mailto:user@example.org
      weight: 8
    - name: RSS
      url: /articles/index.xml
      weight: 9
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    style: dracula
